parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64

- name: pool
  type: string
  values:
  - sonicbld
  - sonicbld-arm64
  - sonicbld-armhf
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: artifact_name
  type: string

- name: run_unit_test
  type: boolean
  default: false

- name: archive_gcov
  type: boolean
  default: false

- name: debian_version
  type: string
  default: bullseye

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}
  variables:
    DIFF_COVER_CHECK_THRESHOLD: 80
    ${{ if eq(parameters.run_unit_test, true) }}:
      DIFF_COVER_ENABLE: 'true'

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ else }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}

  steps:
  - checkout: self
    clean: true
  - script: |
      set -ex
      sudo apt-get update
      sudo apt-get install -qq -y \
        libhiredis-dev \
        libnl-3-dev \
        libnl-genl-3-dev \
        libnl-route-3-dev \
        libnl-nf-3-dev \
        swig
    displayName: "Install dependencies"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-buildimage.common_libs
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      path: $(Build.ArtifactStagingDirectory)/download
      ${{ if eq(parameters.arch, 'amd64') }}:
        artifact: common-lib
      ${{ else }}:
        artifact: common-lib.${{ parameters.arch }}
      patterns: |
        target/debs/${{ parameters.debian_version }}/libyang-*.deb
        target/debs/${{ parameters.debian_version }}/libyang_*.deb
    displayName: "Download libyang from ${{ parameters.arch }} common lib"
  - script: |
      set -ex
      sudo dpkg -i $(find ./download -name *.deb)
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Install libyang from common lib"
  - script: |
      set -ex
      rm ../*.deb || true
      ./autogen.sh
      fakeroot debian/rules DEB_CONFIGURE_EXTRA_FLAGS='--enable-code-coverage' DEB_BUILD_PROFILES=nopython2 CFLAGS="" CXXFLAGS="--coverage -fprofile-abs-path" LDFLAGS="--coverage -fprofile-abs-path" binary
      mv ../*.deb .
    displayName: "Compile sonic swss common with coverage enabled"
  - ${{ if eq(parameters.run_unit_test, true) }}:
    - script: |
        set -ex
        git clone https://github.com/gcovr/gcovr.git
        cd gcovr/
        git checkout 5.2
        sudo pip3 install setuptools
        sudo python3 setup.py install
        cd ..
        sudo rm -rf gcovr
      displayName: "Install gcovr 5.2 (for --exclude-throw-branches support)"

  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss common debian packages"
  - ${{ if eq(parameters.archive_gcov, true) }}:
    - script: |
        set -ex
        # Install .NET CORE
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/debian/11/prod
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
      displayName: "Install .NET CORE"
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
      displayName: 'Publish test coverage'
